apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bbox
  name: bbox
spec:
  initContainers:
  - name: bootstrap
    image: busybox
    command:
    - /bin/sh
    - -c
    - |
      echo Hello from init container
      cat <<EOF > /init/tmp/message.txt
      This is a multi-line
      example of text
      EOF
    volumeMounts:
    - name: tmpdir
      mountPath: /init/tmp
  containers:
    - command:
        - /bin/sh
        - -c
        - |
          echo Hello $WORLD                             
          cat /data/tmp/message.txt  
      env:
        - name: WORLD
          value: world
      image: busybox
      name: bbox
      resources: {}
      volumeMounts:
        - name: tmpdir
          mountPath: /data/tmp
  restartPolicy: Never
  volumes:
    - name: tmpdir
      emptyDir: {}
