apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bbox
  name: bbox
spec:
  initContainers:
  - name: bootstrap
    image: busybox
    command:
    - /bin/sh
    - -c
    - |
      echo Hello from init container
      cat <<EOF > /init/tmp/message.txt
      This is a multi-line
      example of text
      EOF
    volumeMounts:
    - name: tmpdir
      mountPath: /init/tmp
  containers:
  - name: srv
    command:
    - /bin/sh
    - -c
    - |
      echo Hello from server
      cat /data/tmp/message.txt  
      ip -4 a
      cat /data/tmp/message.txt | nc -l -p "$LISTEN_PORT"
    env:
    - name: LISTEN_PORT
      value: "3485"
    image: busybox
    resources: {}
    volumeMounts:
    - name: tmpdir
      mountPath: /data/tmp
  - name: clt
    command:
    - /bin/sh
    - -c
    - |
      echo Starting client
      nc "$HOST" "$PORT"
    env:
    - name: PORT
      value: "3485"
    - name: HOST
      value: "127.0.0.1"
    image: busybox
    resources: {}
  restartPolicy: Never
  volumes:
  - name: tmpdir
    emptyDir: {}
