apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bbox
  name: bbox
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo Hello $WORLD
    env:
    - name: WORLD
      value: world
    image: busybox
    name: bbox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
