apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bbox
  name: bbox-clt
spec:
  containers:
  - name: clt
    command:
    - /bin/sh
    - -c
    - |
      echo Starting client
      nc "$HOST" "$PORT"
    env:
    - name: PORT
      value: "3485"
    - name: HOST
      value: bbox-srv
    image: busybox
    resources: {}
  restartPolicy: Never