apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bbox
  name: bbox
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - echo Hello $WORLD
      env:
        - name: WORLD
          value: world
      image: busybox
      name: bbox
      resources: {}
      volumeMounts:
        - name: tmpdir
          mountPath: /data/tmp
  restartPolicy: Never
  volumes:
    - name: tmpdir
      emptyDir: {}
